included:
  - Sources
  - Tests

excluded:
  - .build
  - harness

line_length:
  warning: 120
  error: 160
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

trailing_whitespace:
  ignores_empty_lines: true

reporter: "xcode"
